### ISSUE TITLE
Advertise IBeacon XPC message has changed in OSX 10.10

### ISSUE THREAD

**Issue by raff** [paypal/gatt#36]
Looks like the IBeacon advertinsing stuff stopped working with OSX 10.10. Just tried today, then looked at the code in bleno and found that for Darwin version >= 14 (I am assuming OSX 10.10 is Darwin 14) there is a new message type.

Look at my changes here:
https://github.com/raff/goble/blob/master/goble.go#L450, copied from bleno.

**Comment by roylee17** [comment]
Would you like to cook a PR for gatt? :-)

**Comment by raff** [comment]
PR #38
