### ISSUE TITLE
HandleWriteFunc not receiving write requests

### ISSUE THREAD

**Issue by kurtng** [paypal/gatt#49]
in the examples/service/count.go if I send a text to the write characteristics then data is empty. Nothing received.

I am testing with Android BLEScanner app to send data and Raspbian OS with BlueZ 5.33 and Plugable BLE usb bluetooth dongle on receiving side.

**Comment by roylee17** [comment]
Hi @kurtng,

I tried the current tip of master, and it works for me.
Does the BLEScanner app send ASCII or HEX values?
On my iPhone, I send something like 0x30313233 with LightBlue app, and the HandleWriteFunc shows:

```015/07/19 02:31:39 Wrote: 0123```
