### ISSUE TITLE
No such file or directory: textflag.h

### ISSUE THREAD

**Issue by patsys** [paypal/gatt#73]
No FIle textflag.h

github.com/paypal/gatt/linux/socket/asm.s:6 6a: No such file or directory: textflag.h

**Comment by afh** [comment]
I'm running into the same issue on Debian 8. What is the proposed solution?

**Comment by alloro** [comment]
Problem could be fixed by updating go. The problem is fixed for the versions >=1.4

**Comment by afh** [comment]
@alloro Thank you. I can confirm that paypal/gatt works with go 1.6.2. I was surprised to find "such an old" version of go (1.3) on the system I was using.

IMHO this issue can be closed.
